---
- name: Configure Samba Share with User Authentication
  hosts: samba_servers
  become: yes
  vars:
    samba_workgroup: "MYGROUP"
    samba_share_name: "private"
    samba_share_path: "/srv/samba/private"
    samba_valid_users: "user1,user2" # Ensure these Linux users exist
    samba_writable: "yes"
    samba_browsable: "yes"
    samba_users:
      - name: "user1"
        password: "password1"
      - name: "user2"
        password: "password2"

  tasks:
    - name: Install Samba Packages
      ansible.builtin.package:
        name:
          - samba
          - samba-common
        state: present

    - name: Ensure Share Directory Exists and Set Permissions
      ansible.builtin.file:
        path: "{{ samba_share_path }}"
        state: directory
        owner: root
        group: "{{ ansible_user_id }}" # Or a specific group
        mode: '0770' # Adjust permissions as needed

    - name: Set Ownership of Share Directory
      ansible.builtin.command: chown root:"{{ ansible_user_id }}" "{{ samba_share_path }}"

    - name: Create Samba Users and Set Passwords
      ansible.builtin.command: "smbpasswd -a -s {{ item.name }}"
      become: yes
      loop: "{{ samba_users }}"
      when: item.name not in samba_existing_users.stdout_lines
      no_log: true # Sensitive data

    - name: Get Existing Samba Users
      ansible.builtin.command: pdbedit -L
      register: samba_existing_users
      changed_when: false

    - name: Configure smb.conf for User Authentication
      ansible.builtin.template:
        src: templates/smb_user.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart smbd nmbd

    - name: Ensure smbd and nmbd services are started and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - smbd
        - nmbd

    - name: Open Samba ports in firewall (if firewalld)
      ansible.builtin.firewalld:
        service: samba
        permanent: yes
        state: enabled
      when: ansible_facts['service_mgr'] == "systemd" and ansible_facts['distribution'] in ["CentOS", "RHEL", "Fedora"]
      notify: Reload firewalld

    - name: Open Samba ports in firewall (if ufw)
      community.general.ufw:
        rule: allow
        port:
          - 137/udp
          - 138/udp
          - 139/tcp
          - 445/tcp
        proto: any
      when: ansible_facts['service_mgr'] == "systemd" and ansible_facts['distribution'] in ["Debian", "Ubuntu"]
      notify: Reload ufw

  handlers:
    - name: Restart smbd nmbd
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - smbd
        - nmbd

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Reload ufw
      community.general.ufw:
        state: reloaded
